# Generated by Django 4.2.7 on 2026-03-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('system_prompt', models.TextField(verbose_name='System Prompt 完整文本')),
                ('change_log', models.TextField(blank=True, default='', verbose_name='变更说明')),
                ('eval_dataset_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联评估数据集ID')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='准确率')),
                ('avg_output_tokens', models.IntegerField(blank=True, null=True, verbose_name='平均输出Token')),
                ('avg_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='平均延迟(ms)')),
                ('hallucination_rate', models.FloatField(blank=True, null=True, verbose_name='幻觉率')),
                ('schema_compliance_rate', models.FloatField(blank=True, null=True, verbose_name='Schema合规率')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前生产版本')),
                ('is_ab_candidate', models.BooleanField(default=False, verbose_name='A/B测试候选')),
                ('ab_traffic_ratio', models.FloatField(default=0, verbose_name='A/B分流比例(0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Prompt版本',
                'verbose_name_plural': 'Prompt版本',
                'db_table': 'ai_requirement_prompt_version',
                'ordering': ['-created_at'],
                'unique_together': {('task_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AiRequirementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('product', '产品'), ('dev', '开发'), ('test', '测试')], max_length=20, verbose_name='角色')),
                ('task_type', models.CharField(choices=[('competitive_analysis', '竞品分析'), ('prd_draft', 'PRD撰写'), ('prd_refine', '需求完善'), ('requirement_analysis', '需求分析'), ('tech_design', '技术方案'), ('test_requirement_analysis', '测试需求分析'), ('feature_breakdown', '功能点梳理')], max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('generating', '生成中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('requirement_input', models.TextField(help_text='用户输入的文本描述', verbose_name='需求描述')),
                ('source_files', models.JSONField(blank=True, null=True, verbose_name='源文件路径列表')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='多轮对话会话ID')),
                ('use_thinking', models.BooleanField(default=False, verbose_name='深度推理模式')),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('markdown', 'Markdown'), ('both', '双形态')], default='both', max_length=20, verbose_name='输出格式')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='结构化结果(JSON)')),
                ('result_md', models.TextField(blank=True, null=True, verbose_name='Markdown结果')),
                ('raw_content', models.TextField(blank=True, null=True, verbose_name='AI原始返回')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='置信度评分')),
                ('schema_validated', models.BooleanField(default=False, verbose_name='是否通过Schema验证')),
                ('validation_retries', models.IntegerField(default=0, verbose_name='Schema验证重试次数')),
                ('model_used', models.CharField(blank=True, default='', max_length=50, verbose_name='使用的模型')),
                ('prompt_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prompt版本号')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='成本(USD)')),
                ('downstream_testcases', models.JSONField(blank=True, default=list, verbose_name='下游用例任务ID列表')),
                ('security_level', models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('confidential', '机密')], default='internal', max_length=20, verbose_name='数据安全等级')),
                ('pii_detected', models.BooleanField(default=False, verbose_name='是否检测到PII')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='ai_requirement.airequirementtask', verbose_name='父任务(修订链)')),
            ],
            options={
                'verbose_name': 'AI需求任务',
                'verbose_name_plural': 'AI需求任务',
                'db_table': 'ai_requirement_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiRequirementFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('positive', '👍'), ('negative', '👎')], max_length=10, verbose_name='评价')),
                ('issue_type', models.CharField(blank=True, choices=[('hallucination', '幻觉'), ('missing', '遗漏'), ('format_error', '格式错误'), ('irrelevant', '不相关'), ('other', '其他')], max_length=30, null=True, verbose_name='问题类型')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='详细说明')),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20, verbose_name='当时的Prompt版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_requirement.airequirementtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '需求智能体反馈',
                'verbose_name_plural': '需求智能体反馈',
                'db_table': 'ai_requirement_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='prompt_injection_blocked / pii_detected / security_level_reject / ...', max_length=50, verbose_name='事件类型')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='关联任务ID')),
                ('detail', models.TextField(verbose_name='事件详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'AI审计日志',
                'verbose_name_plural': 'AI审计日志',
                'db_table': 'ai_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='airequirementtask',
            index=models.Index(fields=['role', 'task_type'], name='ai_requirem_role_323712_idx'),
        ),
        migrations.AddIndex(
            model_name='airequirementtask',
            index=models.Index(fields=['status'], name='ai_requirem_status_40dd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='airequirementtask',
            index=models.Index(fields=['session_id'], name='ai_requirem_session_164b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='ai_audit_lo_event_t_2f78c5_idx'),
        ),
    ]
