# Generated by Django 4.2.7 on 2026-03-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requirement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('title', models.CharField(max_length=200, verbose_name='样本标题')),
                ('input_text', models.TextField(verbose_name='输入文本')),
                ('expected_key_facts', models.JSONField(default=list, verbose_name='期望关键事实列表')),
                ('expected_schema_snapshot', models.JSONField(blank=True, null=True, verbose_name='期望输出 Schema 快照')),
                ('difficulty', models.CharField(default='medium', max_length=10, verbose_name='难度 easy/medium/hard')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评估数据集',
                'verbose_name_plural': '评估数据集',
                'db_table': 'ai_requirement_eval_dataset',
                'ordering': ['task_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态 pending/running/completed/failed')),
                ('total_samples', models.IntegerField(default=0, verbose_name='总样本数')),
                ('completed_samples', models.IntegerField(default=0, verbose_name='已完成样本数')),
                ('trials_per_sample', models.IntegerField(default=3, verbose_name='每样本运行次数')),
                ('avg_accuracy', models.FloatField(blank=True, null=True, verbose_name='平均准确率')),
                ('avg_hallucination', models.FloatField(blank=True, null=True, verbose_name='平均幻觉率')),
                ('avg_schema_compliance', models.FloatField(blank=True, null=True, verbose_name='Schema合规率')),
                ('avg_tokens', models.IntegerField(blank=True, null=True, verbose_name='平均Token')),
                ('avg_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='平均延迟ms')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='总评估成本USD')),
                ('detail_results', models.JSONField(blank=True, null=True, verbose_name='逐样本详细结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='ai_requirement.promptversion', verbose_name='Prompt版本')),
            ],
            options={
                'verbose_name': '评估运行',
                'verbose_name_plural': '评估运行',
                'db_table': 'ai_requirement_eval_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
