# Generated by Django 4.2.7 on 2026-03-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_requirement', '0002_evaldataset_evalrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('prd_deep', 'PRD深度撰写')], default='prd_deep', max_length=30, verbose_name='工作流类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('waiting_approval', '待审批'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('thread_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='LangGraph thread_id')),
                ('requirement_input', models.TextField(verbose_name='原始需求输入')),
                ('use_thinking', models.BooleanField(default=False, verbose_name='深度推理')),
                ('current_node', models.CharField(default='pending', max_length=50, verbose_name='当前节点')),
                ('iteration_count', models.IntegerField(default=0, verbose_name='迭代轮次')),
                ('node_trace', models.JSONField(default=list, verbose_name='节点执行轨迹')),
                ('competitive_analysis', models.JSONField(blank=True, null=True, verbose_name='竞品分析结果')),
                ('prd_draft', models.JSONField(blank=True, null=True, verbose_name='PRD草稿')),
                ('review_score', models.FloatField(blank=True, null=True, verbose_name='评审分数')),
                ('review_feedback', models.TextField(blank=True, null=True, verbose_name='评审反馈')),
                ('final_prd', models.JSONField(blank=True, null=True, verbose_name='最终PRD')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('human_approval', models.BooleanField(blank=True, null=True, verbose_name='人工审批结果')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token消耗')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='总成本USD')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflows', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工作流执行记录',
                'verbose_name_plural': '工作流执行记录',
                'db_table': 'ai_requirement_workflow_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ai_requirem_status_84330c_idx'), models.Index(fields=['workflow_type', 'status'], name='ai_requirem_workflo_85fc68_idx')],
            },
        ),
    ]
