# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requirement', '0003_workflowrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_run_id', models.IntegerField(blank=True, null=True, verbose_name='工作流运行ID')),
                ('span_type', models.CharField(choices=[('llm', 'LLM调用'), ('workflow_node', '工作流节点')], default='llm', max_length=32, verbose_name='类型')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='模型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('error_type', models.CharField(blank=True, help_text='失败时记录错误摘要或类型', max_length=128, null=True, verbose_name='错误类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_call_logs', to='ai_requirement.airequirementtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': 'LLM调用记录',
                'verbose_name_plural': 'LLM调用记录',
                'db_table': 'ai_requirement_llm_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['task', 'created_at'], name='ai_req_llmcall_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['span_type', 'created_at'], name='ai_req_llmcall_span_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['error_type', 'created_at'], name='ai_req_llmcall_error_created_idx'),
        ),
    ]
