# Generated by Django 4.2.7 on 2026-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requirement', '0008_merge_20260314'),
    ]

    operations = []
