# Generated by Django 4.2.7 on 2026-04-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requirement', '0007_remove_llmcalllog_ai_req_llmcall_task_created_idx_and_more'),
        ('ai_requirement', '0009_remove_llmcalllog_ai_req_llmcall_task_created_idx_and_more'),
    ]

    operations = [
    ]
