"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import datetime
import os
import sys
import warnings

from loguru import logger

# 过滤 coreapi 中 pkg_resources 的弃用警告
# coreapi 是 drf-yasg 的依赖，已经是最新版本但仍未修复此问题
warnings.filterwarnings(
    "ignore",
    message="pkg_resources is deprecated.*",
    category=UserWarning,
    module="coreapi",
)

from conf.env import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = locals().get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = locals().get("DEBUG", True)
ALLOWED_HOSTS = locals().get("ALLOWED_HOSTS", ["*"])
# 允许的 CSRF 来源（通过 IP/域名:端口 访问 admin 等表单时必须配置）
CSRF_TRUSTED_ORIGINS = locals().get("CSRF_TRUSTED_ORIGINS", [])

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "django_celery_beat",
    "django_celery_results",
    "channels",  # Django Channels for WebSocket
    "channels_redis",  # Channels Redis support
    "workminduser",
    "apps.ui_test",  # UI测试应用（包含设备管理）
    "apps.ai_testcase",  # AI用例智能体
    "apps.ai_requirement",  # AI需求智能体
    "apps.knowledge_base",  # 知识库
]

MIDDLEWARE = [
    "backend.utils.middleware.PerformanceAndExceptionLoggerMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "log_request_id.middleware.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "backend.asgi.application"
WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DATABASE_NAME or "workmind",
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_HOST or "localhost",
        "PORT": DATABASE_PORT if DATABASE_PORT else 3306,
        "OPTIONS": {
            "charset": "utf8mb4",  # 设置字符集为utf8mb4
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# LangGraph 工作流持久化（SQLite Checkpointer，进程重启可恢复）
# 默认：backend/data/langgraph_checkpoints.sqlite；可通过 LANGGRAPH_CHECKPOINT_DB_PATH 覆盖
LANGGRAPH_CHECKPOINT_DB_PATH = os.environ.get(
    "LANGGRAPH_CHECKPOINT_DB_PATH",
    os.path.join(BASE_DIR, "data", "langgraph_checkpoints.sqlite"),
)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False

# ================================================= #
# *************** REST_FRAMEWORK配置 *************** #
# ================================================= #
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "backend.utils.auth.MyJWTAuthentication",  # 设置全局的默认身份验证方案
    ],
    "UNAUTHENTICATED_USER": None,
    "UNAUTHENTICATED_TOKEN": None,
    # json form 渲染
    # 设置全局默认的解析器集
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",  # 解析 JSON 请求内容
        "rest_framework.parsers.FormParser",  # 解析 HTML 表单内容
        "rest_framework.parsers.MultiPartParser",  # 解析多部分HTML表单内容，支持文件上传
        "rest_framework.parsers.FileUploadParser",  # 解析原始文件上传内容
    ],
    "DEFAULT_PAGINATION_CLASS": "backend.utils.pagination.MyPageNumberPagination",  # 默认分页器
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # 有经过身份认证确定用户身份才能访问
    ),
    # 限流（仅对设置了 throttle_scope 的接口生效）
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # AI 用例生成相关高成本接口（可按需调整）
        "ai_testcase": "50/min",
    },
}

# ================================================= #
# ******************* CORS 白名单 ******************* #
# ================================================= #
# ai_testcase SSE 接口需要跨域直连时，建议只放行你们的前端域名（不要用 "*")
# 例：["http://localhost:3000", "https://workmind.example.com"]
AI_TESTCASE_CORS_ALLOW_ORIGINS = [
    # 只允许 Origin（不含路径）
    "http://172.13.6.230:8080",
    "http://localhost:8888",
]

# 用于追踪提示词/生成策略版本（建议发布时递增）
AI_TESTCASE_PROMPT_VERSION = "v1"

# 幂等复用窗口（秒）：同一用户在该窗口内重复提交相同输入，将直接复用最近一次 success 结果
AI_TESTCASE_IDEMPOTENCY_REUSE_WINDOW_SECONDS = 60

# ================================================= #
# ****************** simplejwt配置 ***************** #
# ================================================= #
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = "workminduser.MyUser"

# ====================================#
# ****************swagger************#
# ====================================#
SWAGGER_SETTINGS = {
    "DEFAULT_AUTO_SCHEMA_CLASS": "backend.utils.swagger.CustomSwaggerAutoSchema",
    "SECURITY_DEFINITIONS": {
        "Token": {"type": "apiKey", "name": "Authorization", "in": "header"},
    },
    # 接口文档中方法列表以首字母升序排列
    "APIS_SORTER": "alpha",
    # 如果支持json提交, 则接口文档中包含json输入框
    "JSON_EDITOR": True,
    # 方法列表字母排序
    "OPERATIONS_SORTER": "alpha",
    "VALIDATOR_URL": None,
    "USE_SESSION_AUTH": False,
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/django_static/"

# 指定static文件的路径，缺少这个配置，collectstatic无法加载extent.js
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# collectstatic 之后的文件存放路径
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 配置 loguru 日志
# 注意：在 Windows 上，如果文件被其他进程占用，轮转可能会失败
# 使用按大小轮转，并添加延迟初始化，避免启动时的文件冲突
logs_dir = os.path.join(BASE_DIR, "logs")
os.makedirs(logs_dir, exist_ok=True)

# 移除默认的 stderr handler，避免重复输出
logger.remove()

for level in ["INFO", "WARNING", "ERROR"]:
    log_file = os.path.join(logs_dir, f"{level.lower()}.log")
    try:
        # 使用按大小轮转，避免启动时的时间轮转冲突
        logger.add(
            log_file,
            format="{time:YYYY-MM-DD HH:mm:ss.SSS}"
                   " [pid:{process} -> thread:{thread.name}]"
                   " {level}"
                   " [{name}:{function}:{line}]"
                   " {message}",
            level=level,
            rotation="100 MB",  # 按大小轮转，避免时间轮转时的文件冲突
            retention="14 days",  # 保留14天
            compression="zip",  # 压缩旧日志
            encoding="utf-8",  # 使用 UTF-8 编码，支持 emoji 和中文
            enqueue=True,  # 使用队列，避免多进程写入冲突
            catch=True,  # 捕获异常，避免日志配置错误导致程序崩溃
            backtrace=False,  # 禁用回溯，减少日志大小
            diagnose=False,  # 禁用诊断信息，减少日志大小
            delay=True,  # 延迟打开文件，避免启动时的文件冲突
        )
    except Exception as e:
        # 如果日志配置失败（如文件被占用），只输出到控制台
        print(f"Warning: Failed to configure loguru file handler for {level}: {e}", file=sys.stderr)
        logger.add(
            sys.stderr,
            level=level,
            format="{time:YYYY-MM-DD HH:mm:ss.SSS} [{level}] [{name}:{function}:{line}] {message}",
        )

# 添加控制台输出（所有级别）
logger.add(
    sys.stderr,
    format="{time:YYYY-MM-DD HH:mm:ss.SSS} [{level}] [{name}:{function}:{line}] {message}",
    level="INFO",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "standard": {
            "format": "%(levelname)-2s [%(asctime)s] [%(request_id)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "color": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(green)s%(asctime)s [%(request_id)s] %(name)s %(log_color)s%(levelname)s [pid:%(process)d] "
                      "[%(filename)s->%(funcName)s:%(lineno)s] %(cyan)s%(message)s",
            "log_colors": {
                "DEBUG": "black",
                "INFO": "white",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
        }
        # 日志格式
    },
    "filters": {
        "request_id": {"()": "log_request_id.filters.RequestIDFilter"},
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",  # 过滤器，只有当setting的DEBUG = True时生效
        },
    },
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
        "default": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/django.log"),  # 改为 django.log，避免与 loguru 的 info.log 冲突
            "maxBytes": 1024 * 1024 * 50,
            "backupCount": 5,
            "formatter": "color",
            "filters": ["request_id"],
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "color",
            "filters": ["request_id"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["default", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# celery 配置
CELERY_BROKER_URL = MQ_URL  # 消息队列地址
CELERY_RESULT_BACKEND = "django-db"  # celery结果存储到数据库中
CELERY_TIMEZONE = TIME_ZONE  # celery 时区问题
# 使用自定义调度器，避免“小时窗口”优化导致 crontab 任务被误排除不触发
CELERY_BEAT_SCHEDULER = "backend.beat_scheduler.WorkmindDatabaseScheduler"
# True 时 Crontab 的 timezone（如 Asia/Shanghai）才生效，否则 USE_TZ=False 下可能不按点触发（见 django-celery-beat#798）
DJANGO_CELERY_BEAT_TZ_AWARE = True
CELERY_ENABLE_UTC = False  # 时区设置

# 设置请求体的最大大小
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500M

# 设置单个文件的最大上传大小
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

LOG_REQUEST_ID_HEADER = "HTTP_X_REQUEST_ID"
GENERATE_REQUEST_ID_IF_NOT_IN_HEADER = True
REQUEST_ID_RESPONSE_HEADER = "RESPONSE_HEADER_NAME"

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = []

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "VIEW",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

# Django Channels配置（WebSocket支持）
# 使用 Redis Channel Layer，必须确保 Redis 服务运行
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # 使用字符串格式的 Redis URL（推荐方式，支持密码和数据库）
            # 如果 REDIS_PASSWORD 为空字符串或 None，则不使用密码
            "hosts": [
                f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}" 
                if REDIS_PASSWORD and REDIS_PASSWORD.strip()
                else f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
            ],
            "capacity": 1500,  # 消息队列容量
            "expiry": 10,  # 消息过期时间（秒）
        },
    },
}

# 启动时验证 Redis 连接
try:
    import redis
    redis_client = redis.Redis(
        host=REDIS_HOST,
        port=int(REDIS_PORT),
        password=REDIS_PASSWORD if REDIS_PASSWORD else None,
        db=int(REDIS_DB),
        socket_connect_timeout=2,
        socket_timeout=2
    )
    redis_client.ping()
    redis_client.close()
    logger.info(f"✅ Channel Layer: Redis 连接成功 ({REDIS_HOST}:{REDIS_PORT})")
except Exception as e:
    logger.error(f"❌ Channel Layer: Redis 连接失败 ({REDIS_HOST}:{REDIS_PORT}) - {e}")
    logger.error("   请确保 Redis 服务正在运行，WebSocket 功能将不可用")

# ==================== Kimi AI 配置 ====================
# 须在环境变量或项目根目录 .env 中配置 KIMI_API_KEY，勿在仓库中写死密钥
KIMI_API_KEY = os.environ.get("KIMI_API_KEY", "").strip()
KIMI_BASE_URL = os.environ.get("KIMI_BASE_URL", "https://api.moonshot.cn/v1")
KIMI_MODEL = os.environ.get("KIMI_MODEL", "kimi-k2.5")

# ==================== DeepSeek AI 配置（需求智能体备选/增强）====================
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")
DEEPSEEK_R1_MODEL = os.environ.get("DEEPSEEK_R1_MODEL", "deepseek-reasoner")

# ============ AI 用例智能体（P2 多模型路由） ============
AI_TESTCASE_MODEL_GENERATE = os.environ.get("AI_TESTCASE_MODEL_GENERATE", "deepseek-chat")
AI_TESTCASE_MODEL_REVIEW = os.environ.get("AI_TESTCASE_MODEL_REVIEW", "kimi-k2.5")
AI_TESTCASE_MODEL_REFINE = os.environ.get("AI_TESTCASE_MODEL_REFINE", "kimi-k2.5")
AI_TESTCASE_COST_CONFIRM_THRESHOLD_USD = float(os.environ.get("AI_TESTCASE_COST_CONFIRM_THRESHOLD_USD", "0") or 0)
AI_TESTCASE_EVENT_RETENTION_DAYS = int(os.environ.get("AI_TESTCASE_EVENT_RETENTION_DAYS", "7") or 7)

# ==================== 需求智能体 - 视频 ASR（可选）====================
# 开启后，上传视频时会提取音轨并 POST 到下方 URL 获取转写文本，参与竞品分析等生成
# 接口期望：POST application/octet-stream 或 multipart，返回 JSON {"text": "..."} 或纯文本
AI_REQUIREMENT_ASR_ENABLED = os.environ.get("AI_REQUIREMENT_ASR_ENABLED", "false").lower() in ("true", "1", "yes")
AI_REQUIREMENT_ASR_API_URL = os.environ.get("AI_REQUIREMENT_ASR_API_URL", "")

# ==================== 需求智能体 - 数据分级与成本确认（P2-1）====================
# 机密数据强制使用的模型（如本地/私有化 DeepSeek），默认 deepseek-chat
AI_REQUIREMENT_CONFIDENTIAL_MODEL = os.environ.get("AI_REQUIREMENT_CONFIDENTIAL_MODEL", "deepseek-chat")
# 单任务预估成本超过该值（USD）时要求前端确认后再执行，0 表示不确认
AI_REQUIREMENT_COST_CONFIRM_THRESHOLD_USD = float(os.environ.get("AI_REQUIREMENT_COST_CONFIRM_THRESHOLD_USD", "0.5"))
# 成本告警：当日全站成本超过该值（USD）时触发告警并写入 stats，0 表示不告警
AI_REQUIREMENT_COST_ALERT_DAILY_USD = float(os.environ.get("AI_REQUIREMENT_COST_ALERT_DAILY_USD", "0"))
# 成本告警触发时 POST 的 Webhook URL（可选），请求体 JSON: {"date": "YYYY-MM-DD", "total_usd": 1.23, "message": "..."}
AI_REQUIREMENT_COST_ALERT_WEBHOOK = os.environ.get("AI_REQUIREMENT_COST_ALERT_WEBHOOK", "")
# 用户维度配额：单用户当日成本上限（USD），0 表示不限制
AI_REQUIREMENT_USER_DAILY_COST_LIMIT_USD = float(os.environ.get("AI_REQUIREMENT_USER_DAILY_COST_LIMIT_USD", "0"))
# 用户维度配额：单用户当日请求次数上限，0 表示不限制
AI_REQUIREMENT_USER_DAILY_REQUESTS_LIMIT = int(os.environ.get("AI_REQUIREMENT_USER_DAILY_REQUESTS_LIMIT", "0"))

# ==================== 需求智能体 - Jira/Confluence 连接器（P2-3）====================
# Jira：Base URL（如 https://your-domain.atlassian.net）、邮箱、API Token、默认项目 Key
JIRA_BASE_URL = os.environ.get("JIRA_BASE_URL", "")
JIRA_EMAIL = os.environ.get("JIRA_EMAIL", "")
JIRA_API_TOKEN = os.environ.get("JIRA_API_TOKEN", "")
JIRA_PROJECT_KEY = os.environ.get("JIRA_PROJECT_KEY", "")
# Confluence：Base URL、邮箱、API Token、默认空间 Key
CONFLUENCE_BASE_URL = os.environ.get("CONFLUENCE_BASE_URL", "")
CONFLUENCE_EMAIL = os.environ.get("CONFLUENCE_EMAIL", "")
CONFLUENCE_API_TOKEN = os.environ.get("CONFLUENCE_API_TOKEN", "")
CONFLUENCE_SPACE_KEY = os.environ.get("CONFLUENCE_SPACE_KEY", "")

# ==================== 需求智能体 - RAG 长期记忆（P2-4）====================
# 开启后，成功任务会索引到向量库，生成时注入历史 PRD/术语表片段
AI_REQUIREMENT_RAG_ENABLED = os.environ.get("AI_REQUIREMENT_RAG_ENABLED", "false").lower() in ("true", "1", "yes")
# 使用 OpenAI Embedding（需 OPENAI_API_KEY）；未配置则 RAG 不建索引、检索返回空
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
AI_REQUIREMENT_EMBEDDING_MODEL = os.environ.get("AI_REQUIREMENT_EMBEDDING_MODEL", "text-embedding-3-small")
AI_REQUIREMENT_RAG_TOP_K = int(os.environ.get("AI_REQUIREMENT_RAG_TOP_K", "5"))
AI_REQUIREMENT_RAG_MAX_CHARS = int(os.environ.get("AI_REQUIREMENT_RAG_MAX_CHARS", "8000"))

# ==================== 知识库配置 ====================
# Qdrant 向量数据库（推荐部署：docker run -d -p 6333:6333 qdrant/qdrant）
QDRANT_HOST = os.environ.get("QDRANT_HOST", "127.0.0.1")
QDRANT_PORT = int(os.environ.get("QDRANT_PORT", "6333") or 6333)
QDRANT_API_KEY = os.environ.get("QDRANT_API_KEY", "")
# 知识库 Embedding 模型（使用 Kimi API）
KNOWLEDGE_EMBEDDING_KEY = os.environ.get("KNOWLEDGE_EMBEDDING_KEY", "")
KNOWLEDGE_EMBEDDING_BASE_URL = os.environ.get("KNOWLEDGE_EMBEDDING_BASE_URL", "")
KNOWLEDGE_EMBEDDING_MODEL = os.environ.get("KNOWLEDGE_EMBEDDING_MODEL", "moonshot-v1-embedding")
# RAG 检索 Top-K
KNOWLEDGE_RAG_TOP_K = int(os.environ.get("KNOWLEDGE_RAG_TOP_K", "5") or 5)
