# Generated by Django 5.2.10 on 2026-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTestcaseGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(help_text='输入的功能需求描述', verbose_name='需求描述')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('generating', '生成中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('use_thinking', models.BooleanField(default=False, verbose_name='思考模式')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='结构化用例数据')),
                ('raw_content', models.TextField(blank=True, null=True, verbose_name='AI原始返回')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('xmind_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='XMind文件路径')),
                ('module_count', models.IntegerField(default=0, verbose_name='模块数')),
                ('case_count', models.IntegerField(default=0, verbose_name='用例数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI用例生成记录',
                'verbose_name_plural': 'AI用例生成记录',
                'db_table': 'ai_testcase_generation',
                'ordering': ['-created_at'],
            },
        ),
    ]
