# Generated by Django 4.2.7 on 2026-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='source_files',
            field=models.JSONField(blank=True, help_text='["/path/to/file1.pdf", "/path/to/file2.png"]', null=True, verbose_name='源文件路径列表'),
        ),
    ]
