# Generated by Django 4.2.7 on 2026-04-07 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testcase', '0004_aitestcasegeneration_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='用于避免同一用户重复提交导致重复消耗',
                max_length=64,
                null=True,
                verbose_name='幂等键',
            ),
        ),
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='prompt_version',
            field=models.CharField(
                blank=True,
                help_text='用于追踪生成/评审使用的提示词版本',
                max_length=50,
                null=True,
                verbose_name='提示词版本',
            ),
        ),
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='aitestcasegeneration',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '等待中'),
                    ('generating', '生成中'),
                    ('success', '成功'),
                    ('failed', '失败'),
                    ('cancelled', '已取消'),
                ],
                default='pending',
                max_length=20,
                verbose_name='状态',
            ),
        ),
    ]

