# Generated by Django 4.2.7 on 2026-04-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testcase', '0005_aitestcasegeneration_p1_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='current_stage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='当前阶段'),
        ),
        migrations.AddField(
            model_name='aitestcasegeneration',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.CreateModel(
            name='AiTestcaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30, verbose_name='事件类型')),
                ('payload', models.JSONField(default=dict, verbose_name='事件载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'generation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='ai_testcase.aitestcasegeneration',
                        verbose_name='生成记录',
                    ),
                ),
            ],
            options={
                'verbose_name': 'AI用例生成事件',
                'verbose_name_plural': 'AI用例生成事件',
                'ordering': ['id'],
                'db_table': 'ai_testcase_event',
            },
        ),
        migrations.AddIndex(
            model_name='aitestcaseevent',
            index=models.Index(fields=['generation', 'id'], name='ai_tc_event_gen_id_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestcaseevent',
            index=models.Index(fields=['generation', 'created_at'], name='ai_tc_event_gen_ct_idx'),
        ),
    ]

