# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalrequirement',
            name='test_team',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='测试团队'),
        ),
    ]
