# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0002_functionalrequirement_test_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('requirement_name', models.CharField(blank=True, default='', max_length=200, verbose_name='所属需求')),
                ('owner', models.CharField(blank=True, default='', max_length=200, verbose_name='任务负责人')),
                ('status', models.CharField(blank=True, default='未开始', max_length=20, verbose_name='任务状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('man_days', models.CharField(blank=True, default='', max_length=50, verbose_name='任务人日')),
                ('task_time', models.CharField(blank=True, default='', max_length=80, verbose_name='任务时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务管理',
                'db_table': 'functional_task',
                'ordering': ['-updated_at'],
            },
        ),
    ]
