# Generated by Django 4.2.7 on 2026-03-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0004_refactor_functional_test_case_for_ai'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apppackage',
            new_name='ui_test_app_package_c89c87_idx',
            old_name='ui_test_app_pkg_name_idx',
        ),
        migrations.RenameIndex(
            model_name='apppackage',
            new_name='ui_test_app_name_5d4757_idx',
            old_name='ui_test_app_name_idx',
        ),
    ]
