# Generated by Django 4.2.7 on 2026-04-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0005_rename_ui_test_app_pkg_name_idx_ui_test_app_package_c89c87_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaltestcase',
            options={'ordering': ['created_at'], 'verbose_name': '功能测试用例', 'verbose_name_plural': '功能测试用例'},
        ),
    ]
