# -*- coding: utf-8 -*-
# Generated by Cursor on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0006_alter_functionaltestcase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlanCaseOperationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test_plan_logs/%Y/%m/%d/', verbose_name='附件文件')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='文件类型')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ui_test.TestPlanCaseOperationLog', verbose_name='操作记录')),
            ],
            options={
                'verbose_name': '测试计划用例操作附件',
                'verbose_name_plural': '测试计划用例操作附件',
                'db_table': 'test_plan_case_log_attachment',
                'ordering': ['id'],
            },
        ),
    ]

