# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0007_testplancaseoperationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_team',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='测试团队'),
        ),
    ]

